version: "3.9"
services:
    db:
        image: postgres:13-alpine
        environment:
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=db
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
    backend:
        build:
            context: ./backend
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=db
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}
    prestart:
        build:
            context: ./backend
        networks:
            - app-network
        depends_on:
            db:
                condition: service_healthy
                restart: true
        command: bash scripts/pre_start.sh
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=db
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}

volumes:
    db_data:
