services:
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=db
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ADMIN_USER=${ADMIN_USER}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    prestart:
        build:
            context: ./backend
        depends_on:
            db:
                condition: service_healthy
                restart: true
        command: bash scripts/pre_start.sh
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=db
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ADMIN_USER=${ADMIN_USER}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}


volumes:
    db_data:
